// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MultiCameraData.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__MULTICAMERADATA_HPP
#define FAST_DDS_GENERATED__MULTICAMERADATA_HPP

#include <cstdint>
#include <utility>
#include <vector>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MULTICAMERADATA_SOURCE)
#define MULTICAMERADATA_DllAPI __declspec( dllexport )
#else
#define MULTICAMERADATA_DllAPI __declspec( dllimport )
#endif // MULTICAMERADATA_SOURCE
#else
#define MULTICAMERADATA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MULTICAMERADATA_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure ImageData defined by the user in the IDL file.
 * @ingroup MultiCameraData
 */
class ImageData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ImageData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ImageData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData(
            const ImageData& x)
    {
                    m_width = x.m_width;

                    m_height = x.m_height;

                    m_camera110 = x.m_camera110;

                    m_camera100 = x.m_camera100;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData(
            ImageData&& x) noexcept
    {
        m_width = x.m_width;
        m_height = x.m_height;
        m_camera110 = std::move(x.m_camera110);
        m_camera100 = std::move(x.m_camera100);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData& operator =(
            const ImageData& x)
    {

                    m_width = x.m_width;

                    m_height = x.m_height;

                    m_camera110 = x.m_camera110;

                    m_camera100 = x.m_camera100;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData& operator =(
            ImageData&& x) noexcept
    {

        m_width = x.m_width;
        m_height = x.m_height;
        m_camera110 = std::move(x.m_camera110);
        m_camera100 = std::move(x.m_camera100);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ImageData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ImageData& x) const
    {
        return (m_width == x.m_width &&
           m_height == x.m_height &&
           m_camera110 == x.m_camera110 &&
           m_camera100 == x.m_camera100);
    }

    /*!
     * @brief Comparison operator.
     * @param x ImageData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ImageData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            uint32_t _width)
    {
        m_width = _width;
    }

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport uint32_t width() const
    {
        return m_width;
    }

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport uint32_t& width()
    {
        return m_width;
    }


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            uint32_t _height)
    {
        m_height = _height;
    }

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport uint32_t height() const
    {
        return m_height;
    }

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport uint32_t& height()
    {
        return m_height;
    }


    /*!
     * @brief This function copies the value in member camera110
     * @param _camera110 New value to be copied in member camera110
     */
    eProsima_user_DllExport void camera110(
            const std::vector<uint8_t>& _camera110)
    {
        m_camera110 = _camera110;
    }

    /*!
     * @brief This function moves the value in member camera110
     * @param _camera110 New value to be moved in member camera110
     */
    eProsima_user_DllExport void camera110(
            std::vector<uint8_t>&& _camera110)
    {
        m_camera110 = std::move(_camera110);
    }

    /*!
     * @brief This function returns a constant reference to member camera110
     * @return Constant reference to member camera110
     */
    eProsima_user_DllExport const std::vector<uint8_t>& camera110() const
    {
        return m_camera110;
    }

    /*!
     * @brief This function returns a reference to member camera110
     * @return Reference to member camera110
     */
    eProsima_user_DllExport std::vector<uint8_t>& camera110()
    {
        return m_camera110;
    }


    /*!
     * @brief This function copies the value in member camera100
     * @param _camera100 New value to be copied in member camera100
     */
    eProsima_user_DllExport void camera100(
            const std::vector<uint8_t>& _camera100)
    {
        m_camera100 = _camera100;
    }

    /*!
     * @brief This function moves the value in member camera100
     * @param _camera100 New value to be moved in member camera100
     */
    eProsima_user_DllExport void camera100(
            std::vector<uint8_t>&& _camera100)
    {
        m_camera100 = std::move(_camera100);
    }

    /*!
     * @brief This function returns a constant reference to member camera100
     * @return Constant reference to member camera100
     */
    eProsima_user_DllExport const std::vector<uint8_t>& camera100() const
    {
        return m_camera100;
    }

    /*!
     * @brief This function returns a reference to member camera100
     * @return Reference to member camera100
     */
    eProsima_user_DllExport std::vector<uint8_t>& camera100()
    {
        return m_camera100;
    }



private:

    uint32_t m_width{0};
    uint32_t m_height{0};
    std::vector<uint8_t> m_camera110;
    std::vector<uint8_t> m_camera100;

};

#endif // _FAST_DDS_GENERATED_MULTICAMERADATA_HPP_


